### ISSUE TITLE
Permission denied (publickey).

### ISSUE THREAD

**Issue by gklasen** [mysocketio/mysocketctl#14]
Sorry to bother you once more, as done particially in #9 .

But i keep getty the error in the title while running MySocketIO. Can you provide more detailed documentation as done already? I still have major problems setting up.

I generated keys as described here: 
https://git-scm.com/book/en/v2/Git-on-the-Server-Generating-Your-SSH-Public-Key

Created account with the public key in --sshkey flag, renamed pair to id_rsa and id_rsa.pub and moved them to ~/.ssh/. 

What is missing?

**Comment by atoonk** [comment]
Hi Gerrit,
did you observe this in the last few hours? we had a temporary issue which would have resulted in that error.
also, see #13 

Can you try again, and let me know if you still see it? If so , we can troubleshoot more.

**Comment by atoonk** [comment]
If you keep seeing issues, can you send me the result of this:

```
ssh <YOUR SSH USER NAME>@ssh.mysocket.io -i ~/.ssh/id_rsa  -vvv
```

You can find the ssh username with:
```
mysocketctl account show | grep 'ssh username'
```

**Comment by gklasen** [comment]
Has been resolved, reason was (seems like) the one you mentioned. Best regards!
