### ISSUE TITLE
Replace SSH pub key

### ISSUE THREAD

**Issue by hutger** [mysocketio/mysocketctl#24]
Hi Guys, 

First, Nice project... my compliments. 

Question... how can I manage accounts? I would like to replace an SSH key for a created user... how can I do that?

I've also looked for a way to delete an account, but I couldn't figure this out (not even using the API).

Thanks in advance,

/Hutger

**Comment by atoonk** [comment]
Hi Hutger,

Thanks for giving mysocket a spin and reaching out.
Currently, only one key is supported and you can't change it later. I agree this is annoying and it's on the list to fix.
We may actually revamp the whole key management part. 

I'll take a look at this over the next 2 weeks or so. 

For now, feel free to create another account. If you want me to delete your account, just ping me at andree at mysocket io and I can remove it. 

All stuff to add, still in the MVP phase ;)  Will look at this asap.

Cheers
 Andree

**Comment by hutger** [comment]
Hi @andree, thanks for the prompt response. Got you! 👍 

I'm gonna drop you an e-mail message with the removal request then.

Cheers, Hutger
